config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py -ID https://dx.doi.org/10.35097/832 -R oai-pmh -B https://www.radar-service.eu/oai/OAIHandler
          --tool_endpoint http://localhost:9090/v1.0/rda/rda_all
        container: qc.fair_hasty-pink-bulldog
timeout: 5400
